language: python
matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=pep8
    - python: 3.5
      env: TOXENV=coverage
before_install:
- pip install --upgrade pip setuptools
install:
- pip install tox
script:
- tox -e $TOXENV
