#!/bin/bash
#
set -x
app_path="[PATH TO APP]"
while read oldrev newrev ref
do
        branch=`echo $ref | cut -d/ -f3`
        if [[ "master" == "$branch" ]]; then
                git --work-tree=$app_path checkout -f $branch
                cd $app_path
                make deploylive
                echo 'Changes pushed live.'
        fi
done
