---
jwtauth:
  master_secret: 13ad14ebf16dks743793kdsjfi39fe0d47c37d2d

database:
  provider: postgres
  user: yacoma_conduit
  password: '!tiudnoc0!'
  host: localhost
  database: yacoma_conduit
  filename: null
  create_db: null
