---
jwtauth:
<<<<<<< HEAD
  master_secret: 13ad14ebfl9eks743793kdsjfi39fe0dnf0eu5h8
=======
  master_secret: 13ad14ebf16dks743793kdsjfi39fe0dnf0eu5h8
>>>>>>> 48ff833252fa2fdcfef792c373eea318af270539

database:
  provider: postgres
  user: yacoma_conduit
  password: KUBNrkKAZn
  host: localhost
  database: yacoma_conduit
  filename: null
  create_db: null
