---
jwtauth:
  master_secret: 13ad14ebf16dks743793kdsjfi39fe0dnf0eu5h8

database:
  provider: postgres
  user: yacoma_conduit
  password: KUBNrkKAZn
  host: localhost
  database: yacoma_conduit
  filename: null
  create_db: null
